[package]
name = "psp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
comfy-table = "7.1.1"
humansize = "2.1.3"
humantime = "2.1.0"
psutil = "3.3.0"
